package GUI;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.net.URL;
import admin.adminGUI;

/**
 *
 * @author peter
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        System.out.println("hello");
        URL imgPath = getClass().getResource("/images/login.jpeg");
        System.out.println("IMAGE FOUND: " + imgPath);
        initComponents();
        System.out.println("test");
    }
    
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        masuk_btn = new javax.swing.JButton();
        username_m = new javax.swing.JTextField();
        password_m = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        daftar_di_sini = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 155, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 40, 15));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MASUK");

        jPanel2.setBackground(new java.awt.Color(233, 221, 204));

        jLabel5.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 40, 15));
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(193, 40, 15));
        jLabel6.setText("Password :");

        masuk_btn.setBackground(new java.awt.Color(193, 40, 15));
        masuk_btn.setFont(new java.awt.Font("Baskerville", 0, 20)); // NOI18N
        masuk_btn.setForeground(new java.awt.Color(233, 221, 204));
        masuk_btn.setText("Masuk");
        masuk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_btnActionPerformed(evt);
            }
        });

        username_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_mActionPerformed(evt);
            }
        });

        password_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_mActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_m, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(masuk_btn))
                    .addComponent(username_m))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_m, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_m, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(masuk_btn)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel3.setForeground(new java.awt.Color(193, 40, 15));
        jLabel3.setText("Belum punya akun?");

        daftar_di_sini.setForeground(new java.awt.Color(233, 221, 204));
        daftar_di_sini.setText("Daftar di sini");
        daftar_di_sini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_di_siniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daftar_di_sini)
                        .addGap(57, 57, 57)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(daftar_di_sini))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftar_di_siniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_di_siniMouseClicked
        register register_page = new register();
        register_page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_daftar_di_siniMouseClicked

    private void masuk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_btnActionPerformed
        String username = username_m.getText().trim();
            String password = new String(password_m.getPassword());

            // Validasi input kosong
            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "Username atau password tidak boleh kosong!", 
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Koneksi database menggunakan ConnectionDB
            Connection conn = null;
            PreparedStatement pst = null;
            ResultSet rs = null;

            try {
                // Gunakan ConnectionDB yang sudah ada
                conn = config.ConnectionDB.getConnection();

                if (conn == null) {
                    JOptionPane.showMessageDialog(this, 
                            "Tidak dapat terhubung ke database!", 
                            "Database Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Perbaiki query: gunakan Users (huruf besar) dan password_hash
                String sql = "SELECT id_user, password_hash, is_admin FROM Users WHERE username = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);

                rs = pst.executeQuery();

                if (rs.next()) {
                    String hashedPassword = rs.getString("password_hash");
                    int userId = rs.getInt("id_user");
                    boolean isAdmin = rs.getBoolean("is_admin");

                    // Verifikasi password
                    if (verifyPassword(password, hashedPassword)) {
                        // Buat objek User
                        models.User loggedUser = new models.User(userId, username, hashedPassword, isAdmin);

                        JOptionPane.showMessageDialog(this, 
                                "Login berhasil! Selamat datang " + username, 
                                "Success", JOptionPane.INFORMATION_MESSAGE);
                        
                        Session.setSession(userId, username);
                        
                        // Navigasi berdasarkan role
                        if (isAdmin) {
                            new adminGUI().setVisible(true);
                        } else {
                            new MainMenuFrame().setVisible(true);
                        }
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, 
                                "Password salah!", 
                                "Login Failed", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, 
                            "Username tidak ditemukan!", 
                            "Login Failed", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                        "Terjadi kesalahan: " + e.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();

            } finally {
                try { if (rs != null) rs.close(); } catch (Exception e) {}
                try { if (pst != null) pst.close(); } catch (Exception e) {}
                try { if (conn != null) conn.close(); } catch (Exception e) {}
            }
    }//GEN-LAST:event_masuk_btnActionPerformed

    private void username_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_mActionPerformed
        password_m.requestFocus();
    }//GEN-LAST:event_username_mActionPerformed

    private void password_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_mActionPerformed
        masuk_btn.doClick();
    }//GEN-LAST:event_password_mActionPerformed

    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = md.digest(password.getBytes("UTF-8"));

            StringBuilder sb = new StringBuilder();
            for (byte b : hashBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            return null;
        }
    }
    
    private boolean verifyPassword(String plainPassword, String hashedPassword) {
        try {
            String hashedInput = hashPassword(plainPassword);
            return hashedInput != null && hashedInput.equals(hashedPassword);
        } catch (Exception e) {
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
        
        System.out.println("test");


        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftar_di_sini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton masuk_btn;
    private javax.swing.JPasswordField password_m;
    private javax.swing.JTextField username_m;
    // End of variables declaration//GEN-END:variables
}
