package GUI;
import java.net.URL;
import config.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author peter
 */
public class register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(register.class.getName());

    /**
     * Creates new form login
     */
    public register() {
        System.out.println("hello");
        URL imgPath = getClass().getResource("/images/login.jpeg");
        System.out.println("IMAGE FOUND: " + imgPath);
        initComponents();
        System.out.println("test");
    }
    
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        daftar_btn = new javax.swing.JButton();
        username_d = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password_d = new javax.swing.JPasswordField();
        confirmPassword_d = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        masuk_di_sini = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 155, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 40, 15));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DAFTAR");

        jPanel2.setBackground(new java.awt.Color(233, 221, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(295, 270));

        jLabel5.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 40, 15));
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(193, 40, 15));
        jLabel6.setText("Password :");

        daftar_btn.setBackground(new java.awt.Color(193, 40, 15));
        daftar_btn.setFont(new java.awt.Font("Baskerville", 0, 20)); // NOI18N
        daftar_btn.setForeground(new java.awt.Color(233, 221, 204));
        daftar_btn.setText("Daftar");
        daftar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_btnActionPerformed(evt);
            }
        });

        username_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_dActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(193, 40, 15));
        jLabel7.setText("Confirm Password :");

        password_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_dActionPerformed(evt);
            }
        });

        confirmPassword_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassword_dActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_d, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_d)
                            .addComponent(confirmPassword_d)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(daftar_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_d, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_d, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassword_d, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftar_btn)
                .addGap(28, 28, 28))
        );

        jLabel3.setForeground(new java.awt.Color(193, 40, 15));
        jLabel3.setText("Sudah punya akun?");

        masuk_di_sini.setForeground(new java.awt.Color(233, 221, 204));
        masuk_di_sini.setText("Masuk di sini");
        masuk_di_sini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masuk_di_siniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masuk_di_sini)
                        .addGap(57, 57, 57)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(masuk_di_sini))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masuk_di_siniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masuk_di_siniMouseClicked
        login login_page = new login();
        login_page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_masuk_di_siniMouseClicked

    private void daftar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_btnActionPerformed
        String username = username_d.getText().trim();
        String password = new String(password_d.getPassword());
        String confirmPassword = new String(confirmPassword_d.getPassword());

        // Validasi input
        if (username.isEmpty()) {
            showError("Username harus diisi!", username_d);
            return;
        }
        if (password.isEmpty()) {
            showError("Password harus diisi!", password_d);
            return;
        }
        if (confirmPassword.isEmpty()) {
            showError("Konfirmasi password harus diisi!", confirmPassword_d);
            return;
        }
        if (username.length() < 3 || username.length() > 50) {
            showError("Username harus 3–50 karakter!", username_d);
            return;
        }
        if (password.length() < 8 || password.length() > 30) {
            showError("Password harus 8–30 karakter!", password_d);
            return;
        }
        if (!username.matches("^[a-zA-Z0-9_]+$")) {
            showError("Username hanya boleh berisi huruf, angka, dan underscore!", username_d);
            return;
        }
        if (!password.equals(confirmPassword)) {
            showError("Password tidak sesuai!", password_d);
            password_d.setText("");
            confirmPassword_d.setText("");
            return;
        }

        // Cek username sudah ada
        if (isUsernameExists(username)) {
            showError("Username '" + username + "' sudah digunakan!", username_d);
            return;
        }

        // Insert database
        try (Connection conn = ConnectionDB.getConnection()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal!",
                                              "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String query = "INSERT INTO Users (username, password_hash, is_admin) VALUES (?, ?, ?)";
            try (PreparedStatement ps = conn.prepareStatement(query)) {
                String hashedPassword = hashPassword(password);

                ps.setString(1, username);
                ps.setString(2, hashedPassword);
                ps.setBoolean(3, false);

                int rows = ps.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this,
                        "Akun '" + username + "' berhasil didaftarkan!",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE
                    );

                    // Reset form
                    username_d.setText("");
                    password_d.setText("");
                    confirmPassword_d.setText("");

                    // Kembali ke login
                    login login_page = new login();
                    login_page.setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Gagal mendaftarkan akun.",
                                                  "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }//GEN-LAST:event_daftar_btnActionPerformed

    private void showError(String msg, javax.swing.JComponent field) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
        field.requestFocus();
        if (field instanceof javax.swing.text.JTextComponent textField) {
            textField.selectAll();
        }
    }
    private void username_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_dActionPerformed
       password_d.requestFocus();
    }//GEN-LAST:event_username_dActionPerformed

    private void password_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_dActionPerformed
       confirmPassword_d.requestFocus();
    }//GEN-LAST:event_password_dActionPerformed

    private void confirmPassword_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassword_dActionPerformed
       daftar_btn.doClick();
    }//GEN-LAST:event_confirmPassword_dActionPerformed

    private boolean isUsernameExists(String username) {
        String query = "SELECT username FROM Users WHERE username = ?";

        try (Connection conn = ConnectionDB.getConnection();
             PreparedStatement ps = conn.prepareStatement(query)) {

            if (conn == null) return true;

            ps.setString(1, username);

            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    
    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = md.digest(password.getBytes());

            StringBuilder hex = new StringBuilder();
            for (byte b : hashBytes) {
                String h = Integer.toHexString(0xff & b);
                if (h.length() == 1) hex.append('0');
                hex.append(h);
            }
            return hex.toString();

        } catch (NoSuchAlgorithmException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error hashing password", e);
            return "plain:" + password;
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new register().setVisible(true));
        
        System.out.println("test");


        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword_d;
    private javax.swing.JButton daftar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel masuk_di_sini;
    private javax.swing.JPasswordField password_d;
    private javax.swing.JTextField username_d;
    // End of variables declaration//GEN-END:variables
}
